### PR TITLE
feat: Introduce chapter_test parameter and improve code readability

### PR DESCRIPTION
**Pull request by n-WN**
### Summary
This PR introduces a new feature to control chapter quiz handling and includes several code improvements for better maintainability and readability.

### Features Added
- **Chapter Test Parameter**:
  - Added `chapter_test` parameter for configuring how chapter quizzes are handled:
    - `0`: Skip chapter quiz tasks.
    - `1`: Complete the quiz tasks.
  - Implemented logic to skip quiz tasks when `chapter_test` is set to `0`.

### Code Improvements
- **Formatted Code**:
  - Improved code formatting for better readability and consistency.
  - Updated comments to enhance clarity and understanding.
- **Reduced Non-ASCII Usage**:
  - Replaced some non-ASCII characters in the codebase with ASCII equivalents to improve compatibility and avoid potential issues.

### Motivation
Many users do not have a `tiku` token configured and prefer not to use random answers for chapter quizzes. The `chapter_test` parameter provides flexibility to customize behavior while avoiding unnecessary tasks.

### Changes
- Added chapter test logic in `main.py` (lines 255-259).
- Formatted code and revised wording in comments.
- Reduced non-ASCII usage to improve compatibility.

### Related Issues
- N/A

### Additional Notes
The PR includes merged changes from the upstream repository and resolves any conflicts with prior updates.

### CODE REVIEW

**Comment by Samueli924** [comment]
目前@sz134055的配置文件模式已经能提供是否开启题库的选项，不是很有必要再加一个配置参数

**Comment by n-WN** [comment]
> 目前@sz134055的配置文件模式已经能提供是否开启题库的选项，不是很有必要再加一个配置参数

PR The new parameter is to configure whether or not to do the question; 

Release version of the question bank options for the off will still randomly do the question, randomly do the subsequent questions if you do it manually, multiple-choice questions to be deselected, more trouble

**Comment by n-WN** [comment]
> 目前@sz134055的配置文件模式已经能提供是否开启题库的选项，不是很有必要再加一个配置参数

The newly added parameter in the PR is to configure whether to attempt the questions.
When the Tiku option for the Release version is set to "off," questions will still be randomly selected. If answers are filled out randomly and then manually corrected, multiple-choice questions require deselecting incorrect options, which can be a bit cumbersome.

**Comment by n-WN** [comment]
@sz134055 plz review

**Pull request closed without merging**
